# Oral History as Data (OHD) - a Lib-STATIC Tool
# https://github.com/uidaholib/oral-history-as-data

# Site settings

# title of site appears in banner
title: Oral History (as) Data
# tagline appears in banner
tagline: analyze and publish coded oral history and qualitative interviews
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Lib-Static Oral History / Qualitative Interview Analysis Tool, Analyze and publish transcriptions with tagged csvs"
# keywords appear in meta tags
keywords: "university of idaho, oral history, digital collections, digital humanities"
# creator of the digital collection, to appear in meta tags
author: dcnb
# creator contact email for meta tags
email: dbecker@uidaho.edu
# collection project date, when did you publish this web site
collection-date: "2018"

# url is your gh-pages base, following the pattern: username.github.io
url: https://uidaholib.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /oral-history-as-data
# repository is the github repository's full url
repository: https://github.com/uidaholib/oral-history-as-data

# IF you are hosting your interviews at Vimeo, Soundcloud or Youtube, use this section to detail the service and, if necessary, your userid
av_source: youtube #[options: youtube, soundcloud, or vimeo]
soundcloud-id: 

# google services [optional!]
# leave these blank or comment out to NOT include google code
google-tracking-id: "UA-76328753-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

# Jekyll collections settings
collections:
  transcripts:
    output: true
    permalink: /:collection/:name
  howto:
    output: true
    permalink: /:collection/:name
# defaults
defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: howto
    values:
      layout: howto

# Build settings
markdown: kramdown
